### PR TITLE
Add `targetBranch` to work as a PR to push the changes into.

### PR DESCRIPTION
**Pull request by shunkakinoki**
right now, the configuration is limited to only the default `branch.name` parameter. add a `targetBranch` parameter to push as a pull request.

### CODE REVIEW

**Comment by pvdlg** [comment]
There is no guarantee this target branch would be up to date with the current branch. So in such case the push would fail.

Pushing to a different branch would not work in the semantic-release workflow as the push commit would not be included in the release tags. It would also make the local branch ahead of the remote one, which would prevent semantic-release to push the release tag. 

Why would you want to push the release commit to a different branch?

**Comment by shunkakinoki** [comment]
@pvdlg I was thinking of a situation in which the release bot (@semantic-release-bot) did not have administrator access to the PR, hence pushing to a different branch as a pull request. However, giving the release bot administrator access is definitely the best option, as defined the docs

**Comment by shunkakinoki** [comment]
Appreciate this amazing work!

**Comment by shunkakinoki** [comment]
Closing

**Pull request closed without merging**
