### PR TITLE
feat: add package-lock.json to list of automatically detected files

### PR DESCRIPTION
**Pull request by smhxx**
Hi there!

~~npm 5.0 (released in late May of 2017) introduced a new lockfile format to replace `npm-shrinkwrap`, which is instead stored in a file called `package-lock.json`.~~ *(EDIT: I now realize that this explanation isn't exactly correct, although keeping both updated is still something which I believe should be done.)* This PR adds `package-lock.json` to the list of automatically detected files to update, as it also contains the current version number of the package and this will be bumped by `npm version`. Since the latest versions of npm now create `package-lock` files rather than `npm-shrinkwrap` files, it seems appropriate to include both in the list of files that are updated by default.

Cheers!

### CODE REVIEW

**Comment by smhxx** [comment]
Okay, sorry about the commit spam there... had some issues with `git config core.autocrlf` causing `xo` to freak out over every single line in the repository, which made it very difficult to figure out what it actually wanted me to change. Everything should be good now. 😂

**Comment by pvdlg** [comment]
The `package-lock.json` is not a replacement for `npm-shrinkwrap.json`. That's 2 really different things.

The `npm-shrinkwrap.json` is used to lock dependencies when your library is used by your users. The `package-lock.json` is used to lock dependencies when you do `npm install` at the root of your project. In other terms, `npm-shrinkwrap.json` is published on npm and used in production, `package-lock.json` is not published on npm and used only in dev.

semantic-release doesn't use `npm version` because this command in addition of updating the `package.json`, `npm-shrinkwrap.json` and `package-lock.json` also create a commit and a tag. sematnic-release handle things differently. In the out npm plugin we update `package.json` and `npm-shrinkwrap.json` directly.

So the version in `package-lock.json` is not updated, because `package-lock.json` is not published. Also as far as I know the version field in `package-lock.json` is not used anywhere (for info `yarn.lock` which the yarn equivalent doesn't contains the version property).

When you use semantic-release, the `package-lock.json` in your repo will have the version set to `0.0.0-development` which make sense as `package-lock.json` is used only in development.

For all these reason we don't update `package-lock.json` and therefore there is no reason to commit by default (or at all).

Is there any specific reason for which you want to update and commit the version field in `package-lock.json`?

**Comment by smhxx** [comment]
Oooh, interesting. I was aware of what `package-lock` did, but I was under the (apparently mistaken) impression that `npm-shrinkwrap` had the same purpose.

My only reason for wanting `package-lock.json` to be updated is that I use `semantic-release` in conjunction with [Renovate](https://github.com/renovateapp/renovate), which is like Greenkeeper in that it opens PRs to bump your dependencies when new versions come out. Often, these PRs come in several at a time, and if the version number in `package-lock.json` is out-of-date, each PR will attempt to correct it — meaning that as soon as one of the PRs has been merged into master, GitHub will detect a merge conflict in all of the other Renovate PRs, and by default Renovate's behavior is to instantly close and trash all of them when that happens (even though, in reality, a rebase-and-merge would still be trivial to accomplish.)

My initial judgement was that this unwanted interaction was best fixed in `semantic-release`, rather than Renovate, since the former technically *was* leaving an incorrect version number in `package-lock.json`; now that I understand the full picture, I suppose I should do some more investigation to determine whether it makes more sense to have `semantic-release` actually track the version number in `package-lock.json` as it does in `package.json` (which seems like it should be easy,) or to have Renovate ignore it as `semantic-release` does.

I'd tend to lean towards the opinion that using the real version number in the lockfile is preferable, since when npm generates one, it matches the version number to the one specified in the main `package.json`, and it seems to make sense to me to preserve this parity across updates, especially since the "fake" version number is going to be overwritten any time someone updates the lockfile manually. Maybe there is a use case I'm not thinking of where this isn't desired, though.

**Comment by smhxx** [comment]
To clarify, are you saying that the preferred method of maintaining `package.json` and `package-lock.json` files in conjunction with `semantic-release` is to set the version property to "0.0.0-development" in *both* and never update either value in the repository?

**Comment by smhxx** [comment]
Okay, I'm going to delete my previous two comments because I realized I was explaining things in a really weird and roundabout way, and it's actually much simpler than I was making it out to be.

---

First off, thanks for explaining that nuance between shrinkwrap and lockfiles; I haven't actually used shrinkwrap in the past, and mistakenly assumed it served the same purpose as a lockfile. Good to know.

The core of the issue I'm looking to address, I've now realized, can be demonstrated using only `@semantic-release/git` and the normal behavior of `npm install`. While it isn't a "bug," per se, it's still a strange inconsistency that is capable of confusing some dependency management tooling such as Greenkeeper and Renovate.

I'm gathering that there are essentially two different methods of maintaining package "meta" files that are offered by `semantic-release`. There's the method used by `semantic-release` itself, where you set the version number to something like 0.0.0-development and *never* change it on the repository. During CI, `semantic-release` determines the "correct" version number and publishes it, but it's never pushed back to the repo, so the version is *always* 0.0.0 as far as the checked-in copy of `package.json` is concerned. Everything works fine.

However, things get a little more complicated once you factor in `@semantic-release/git`'s alternate method of doing things, where package.json *is* updated upon release. Any time dependencies are added to or removed from a package and `npm install` is run, npm will generate a completely new lockfile, which it will "force" to match the version in `package.json` — if you're not using `@semantic-release/git`, this version is always 0.0.0 or whatever it started as, so nothing extraordinary happens. If you *are* using it, though, that version **isn't** 0.0.0, it's whatever the current version of the package is. So you get a new lockfile with the version set to... let's say 1.4.6, to give an arbitrary example. Now, `npm version` would normally keep this version number in-sync with the version in package.json; however, since `semantic-release` doesn't use `npm version`, these numbers can become desynchronized — you might have a `package.json` version of 2.5.2 and a `package-lock.json` that's still on 1.4.6.

Like you said in your response, this shouldn't matter in theory; it's weird, and perhaps undesirable if you happen to care about it, but npm itself isn't going to complain. However, since it departs from the "normal" behavior of npm, it does have the capability to confuse and cause conflicts with dependency management tooling like Renovate and Greenkeeper, and lead to unexpected merge conflicts when multiple dependencies need to be updated at the same time (due to multiple pull requests both trying to "correct" the lockfile's version number.)

My proposal, which I can also open a PR for, is to have `@semantic-release/npm` set the lockfile's version number to the correct version like it already does for `package.json` before publishing. Ultimately, there's no reason for it *not* to... if the user isn't using `@semantic-release/git`, it will never be committed, anyway. If they do, it will allow *both* package files to be bumped to thr correct version simultaneously, which eliminates the conflicts that having an outdated version number in the lockfile can cause. Hope that makes sense. Thanks for your time!

**Comment by pvdlg** [comment]
I wasn't aware of the behavior you are describing with `npm` when there is inconstancies between the version in `package.json` and `package-lock.json`.

I'm not really aware of any issue with GreenKeeper, but apparently you are experiencing it with Renovate. I'm not sure Renovate behave as it should in that situation, it's arguable it might be a bug on their side. I'm not really sure. Anyway, it seems it's easier to fix in semantic-release than it would on their side and it makes sense to keep things consistent between `package.json` and `package-lock.json`.

Overall you are making a very compelling case.

I opened semantic-release/npm#48 (it was a bit more complex than just adding `package-lock.json` as I has to revert some changes I made earlier to make it work).
Once it's merged we can merge this PR.

**Comment by smhxx** [comment]
Ah, I see what you mean with the other changes in `semantic-release/npm`. Using regex to find the correct version number to bump is a bit more complicated for the lockfile format, since there are potentially many properties called "version" throughout the file. You might not *necessarily* have to revert those changes if you like the idea of using regex to do the replacement; something like `({[^{]*?"version"\s*:\s*")\S+?(\s*")` might work, i.e. "only match 'version' fields that occur before the second open-curly-brace." It's not a *perfect* substitute for the "require, replace, re-write" approach, but AFAIK npm will always put the package version before the dependencies in the lockfile, so if using regex to bump the version is something which is desirable, it might still be possible to achieve that.

**Comment by pvdlg** [comment]
Yep but I also found other issues with the regexp. For example if you have something like that:
```json
{
  "version": "0.0.0",
  "config": {
    "version": "1.0.0"
  }
}
```

The `version` under `config` has nothing to do with the package version, and is just a random config param that happens to be named `version`. 
And I'm sure their might be some other edges cases.

I've been thinking about changing that for a while, as I wan't fully satisfied with the regexp. As explained in semantic-release/npm#48, we now format the same way as `npm version` and `npm install XXX`, so I don't think is much cases in which we are actually going to change the format of the `package.json`.

**Comment by pvdlg** [comment]
I had the concern as well, but there is good arguments:
- Not doing so appear to create an issue with Renovate
- Standard use of npm would do it as well (i.e. using `npm version`)
- It seems more "consistent"

Ideally the npm plugin should use a standard npm command to bump the version, so npm would maintain all that. Unfortunately it's not possible as `npm version` also create a commit, a tag and push them. I think Yarn has CLI options to skip the commit/tag.

So I think we should go ahead with this change for now. In the meantime we can open an issue with npm to request a `skip-git` option that would allow to just update the version in whatever file npm manage (as of now `package.json`, `package-lock.json` and `npm-shrinkwrap.json`). If it gets implemented we'll simplify the npm plugin by just calling `npm version --skip-git` rather than changing files manually as we do now.

We can also open an issue with npm asking why the `package-lock.json` contains the version as it's redundant and apparently useless (`yarn.lcok` doesn't have it).

**Comment by gr2m** [comment]
> We can also open an issue with npm asking why the package-lock.json contains the version as it's redundant and apparently useless (yarn.lcok doesn't have it).

good point, that sounds like the right solution to me. 

Okay, thanks for the explanations, let’s move forward with it :)

**Pull request merged**
