### PR TITLE
feat: add pushFlags support to allow force push on commits

### PR DESCRIPTION
**Pull request by mikebrant-xdelivery**
Hoping to add ability to pass basic options flags to `git push` operation in prepare.  This was primarily intended to enable force pushes for use cases like when working with protected branches in CI environments like Github. 

Also supports dry-run and verbose flags.

### CODE REVIEW

**Comment by travi** [comment]
> use cases like when working with protected branches in CI environments like Github

please provide some context for why this is necessary. we havent seen a request like this among our many users before, so i'm curious what your use case is that isnt satisfied by existing behavior

**Comment by mikebrant-xdelivery** [comment]
> > use cases like when working with protected branches in CI environments like Github
> 
> please provide some context for why this is necessary. we havent seen a request like this among our many users before, so i'm curious what your use case is that isnt satisfied by existing behavior

Current behavior only allows for a `git push --tags ...` configuration during prep step.  I was primarily hoping to enable to the ability to add `--force` option to `git push`.  In my case, this is needed to allow Github Actions release workflow to circumvent branch protection configurations, including pull request approval when making the release commit/tag. Without this, we cannot make the all important release commits without either turning off branch protection (which we do not want to do) or simply dropping use of this plugin in favor of explicit `git` commands in `exec` plugin.

**Comment by travi** [comment]
> this is needed to allow Github Actions release workflow to circumvent branch protection configurations, including pull request approval when making the release commit/tag

i'm not aware of `--force` being an option for bypassing branch protection. this does not sound like behavior that github would allow, since it then allow any user to bypass that protection, if i'm understanding you correctly. can you provide a link to documentation that describes the situations where this is allowed by github?

our normal recommendation for pushing commits with this plugin is to use a PAT instead of the GITHUB_TOKEN that is provided to the action by default. if that token is for an account that is an admin of the repo (preferable a dedicated bot account), the branch protection can be configured to allow admins the ability to bypass the protection.

so that we have a bit more context around your use case, could you describe the changes that you are committing as part of your workflow. these complexities are some of the reasons that we recommend github releases over changelogs and tags over files for tracking version numbers, so it would be helpful to understand your need beyond those recommendations.

**Comment by mikebrant-xdelivery** [comment]
Abandoning this PR, as I agree with commentary on this being an unusual approach. Luckily was able to get our overall workflow changed to disallow force push altogether.

**Comment by travi** [comment]
thanks for following up and closing this out. making this all work with the permission options available can be tough. 

glad the conversation was helpful. in the future, if you start by opening a discussion, we may be able to save you the effort of putting a PR together. the content of your PR looked like a strong contribution, so apologies that it wasnt something that was appropriate to move forward with.

**Pull request closed without merging**
