### PR TITLE
feat: allow 'git commit' and 'git push' during the prepare and/or publish step

### LINKED ISSUE #123: Request: Support Maven releases
[maven logo](https://maven.apache.org/)

### _TL;DR_

Maven's release cycle includes two commits, the first of which is tagged. I would like to expand the capabilities of `@semantic-release/git` to support the Maven release flow.

### What is Maven?

Maven is the de-facto build and dependency management tool for Java. The configuration file for Maven is the `pom.xml` file, which typically can be found at the root of the project. Not too different from NPM's `package.json` file, the `pom.xml` file includes versioning, dependencies, build and test configurations, and distribution information.

### How does Maven version?

Unlike NPM libraries, a Maven repository at rest represents itself with a "snapshot" version number like _1.0.0-SNAPSHOT_. Building a maven project is almost always synonymous with installing a "snapshot" build into the local repository of dependencies. When versioned with "snapshot" numbering, a Maven repository is a dev and testing phase, which is almost always the case.

Released Maven artifacts are versioned how you would expect based on semantic versioning like _1.0.0_. An artifact versioned like this represents one that is "released" or in "general availility" or any other way of saying that it's ready for widespread use.

Maven knows the difference between _1.0.0-SNAPSHOT_ and _1.0.0_. Specifically, it knows that the former always precedes the latter.

### What is a Maven release?

When an artifact is released using Maven, the versioning goes from "snapshot" to semver to the next "snapshot".

In practice you might expect an artifact's version to change like follows:

1. pre-release:  `<version>1.0.0-SNAPSHOT</version>`
2. released:     `<version>1.0.0</version>`
3. post-release: `<version>1.0.1-SNAPSHOT</version>`

### How does a Maven release affect SCM?

In SCM, it is standard for the tagged commit to reference to the point at which the version represented the release (_1.0.0_).

Therefore, minimally a repository has three commits for a single release: 

- one commit before the tag
	- This is the last commit before starting the release script.
	- current version: _1.0.0-SNAPSHOT_
- one commit which is tagged
	- This commit represents the state of the code during artifact deploy.
	- The release script creates this commit prior to tagging.
	- current version: _1.0.0_
- one commit after the tag
	- This commit prepares the repository for continued development.
	- The release script creates this commit after tagging.
	- current version: _1.0.1-SNAPSHOT_

### How does this relate to `@semantic-release/git`?

Dealing with Maven's release cycle means ideally, two commits need to be made during the overall release, and minimally, any `git push` execution occurs only _after_ these commits exist.

More specifically:

1. The _1.0.0_ change and subsequent commit should be created during the `prepare` step, before the tag and before code is published.
2. While in this _1.0.0_ state, the created commit can be tagged.
3. Still in the _1.0.0_ state, the code should be built and published. This makes the most sense to occur during the `publish` step.
4. To complete the release, the code must be prepared for future work by incrementing back to a "snapshot" number, a change which needs to be committed and pushed to SCM. IMO, this is fine to occur either during `publish` or `success` step, but I expect `semantic-release` to consider this relevant to the `publish` step.

What I would like to see from `@semantic-release/git` is flexibility to create a commit during `prepare` _and_ during `publish`. This does not have to be the default functionality, but allowing for it makes it possible to release with Maven without resorting to `@semantic-release/exec` for SCM actions.

My proposal is available at https://github.com/semantic-release/git/pull/122.

### Further Notes

- It should be noted that the Maven "snapshot" versioning and release versioning is more than just practice. Maven has built-in rule-sets and assumptions about how to deal with artifacts versioned like _1.0.0-SNAPSHOT_ versus _1.0.0_.
- While I'm personally not against the arguments made by `semantic-release` for versioning at-rest artifacts like `0.0.0-development` – it is exactly how I treat my _NPM_ artifacts – it just doesn't fit with Maven.

### PR DESCRIPTION
**Pull request by jfairley**
Updates the plugin to allow for commit and push to execute during "prepare" or "publish" or both. By default, commit and push executes during the "prepare" step.

### Examples

The default configuration executes commit/push during "prepare":

```js
module.exports = {
	plugins: [
		['@semantic-release/git', {
			assets: ['pom.xml'],
			message: 'my message'
		}]
	]
};
```

A user may choose to explicitly call out the "prepare" step:

```js
module.exports = {
	plugins: [
		['@semantic-release/git', {
			prepare: {
				assets: ['pom.xml'],
				message: 'my message'
			}
		}]
	]
};
```

A user may choose to execute commit/push during the "publish" step:

```js
module.exports = {
	plugins: [
		['@semantic-release/git', {
			publish: {
				assets: ['pom.xml'],
				message: 'my message'
			}
		}]
	]
};
```

A user _may_ choose to execute commit/push during the "prepare" _and_ "publish" steps:

```js
module.exports = {
	plugins: [
		['@semantic-release/git', {
			prepare: {
				assets: ['pom.xml'],
				message: 'my prepare message'
			},
			publish: {
				assets: ['pom.xml'],
				message: 'my publish message'
			}
		}]
	]
};
```

Finally, the old-school plugin definitions are also supported:

```js
module.exports = {
	prepare: [{
		path: '@semantic-release/git',
		assets: ['pom.xml'],
		message: 'my prepare message'
	}],
	publish: [{
		path: '@semantic-release/git',
		assets: ['pom.xml'],
		message: 'my publish message'
	}]
};
```

closes #121 
closes #123

### CODE REVIEW

**Comment by jfairley** [comment]
I'm having test parallelism issues, because there's multiple "commit" integration tests. Still working on it.

**Comment by pvdlg** [comment]
You opened 2 PRs but in none of them, as far as I can tell, you made the case for implementing a new feature. We won't consider any feature or new option without without a strong case supporting its merit.

I'm not really sure what workflow you are trying to support, but at minimum you have to explain what problem you are trying to solve, why it's the best way to solve this problem and how it can benefit semantic-release users in general.

For information, it's quite unlikely that we would modify our core plugins to support a very specific workflow used by a handful of users. Such cases should be covered with custom plugins.
Keep in mind that an additional option might not seems much but in reality it means more code/tests for us to maintain on the long run, more information to digest for users and ultimately more support tickets for us to handle.

If the feature you are trying to implement would bring value for the overall community and you can make the case for it we will definitely consider it.

**Comment by jfairley** [comment]
@pvdlg I appreciate your feedback. I'll open a simple "issue" to lay out my problem statement. Family needs pending (😉), I'll work on that later tonight.

**Comment by pvdlg** [comment]
Closing per https://github.com/semantic-release/git/issues/123#issuecomment-556923325

**Pull request closed without merging**
