### PR TITLE
feat: wip: use native git env vars instead of custom ones

### PR DESCRIPTION
**Pull request by sergeybekrin**
WIP, follow up for semantic-release#36

### CODE REVIEW

**Comment by sergeybekrin** [comment]
@pvdlg I will continue on this PR to finish tests later, meanwhile could you please check if general implementation is correct? Thanks.

**Comment by pvdlg** [comment]
Thanks for the PR!

Reading your code I realize there is several edge cases that I didn't think about that are not covered.
For example if the user set `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` you want to preserve those value and not override them. Or if the user set `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` but don't set `GIT_COMMITTER_NAME` and `GIT_COMMITTER_EMAIL`, you want to use the default values only for `GIT_COMMITTER_NAME` and `GIT_COMMITTER_EMAIL`.

Seeing the code I also realize it might be convenient to have a variable that allow to set both author and committer value. So maybe we could not deprecate `GIT_USERNAME` and `GIT_EMAIL` and use them for that purpose. What do you think?

Regarding the code organization I would propose that for `resolve-config.js`:
```js
module.exports = ({message, assets}) => ({
  gitAuthorName: process.env.GIT_AUTHOR_NAME || process.env.GIT_USERNAME || DEFAULT_NAME,
  gitAuthorEmail: process.env.GIT_AUTHOR_EMAIL || process.env.GIT_EMAIL ||DEFAULT_EMAIL,
  gitCommitterName: process.env.GIT_COMMITTER_NAME || process.env.GIT_USERNAME || DEFAULT_NAME,
  gitCommitterEmail: process.env.GIT_COMMITTER_EMAIL || process.env.GIT_EMAIL ||DEFAULT_EMAIL,
  message,
  assets: assets ? castArray(assets) : assets,
});
```

And in `prepare.js`:
```js
const {gitAuthorName, gitAuthorEmail, gitCommitterName, gitCommitterEmail, message, assets} = resolveConfig(pluginConfig);

process.env.GIT_AUTHOR_NAME = process.env.GIT_AUTHOR_NAME || gitUserName;
process.env.GIT_AUTHOR_EMAIL = process.env.GIT_AUTHOR_EMAIL || gitUserEmail;
process.env.GIT_COMMITTER_NAME = process.env.GIT_COMMITTER_NAME || gitUserName;
process.env.GIT_COMMITTER_NAME = process.env.GIT_COMMITTER_EMAIL || gitUserEmail;
```

This way we separate the config retrieval, and the config usage. That would allow more flexibility later on if we want to allow to set those parameters via config file, or do something else with it.

Finally, can you remove the unrelated modifications in `README.md` and `package.json`?

**Comment by pvdlg** [comment]
I see that you have formatting errors. You can install [an XO editor plugin](https://github.com/xojs/xo#editor-plugins) to display the errors in your editor and fix them on save.
You can also install xo and fix the error via command line:
```bash
npm install -g xo
xo --fix
```

**Comment by pvdlg** [comment]
Finally I think we could move all the code setting `GIT_AUTHOR_NAME`, `GIT_AUTHOR_EMAIL`, `GIT_COMMITTER_NAME` and `GIT_COMMITTER_EMAIL` in semantic-release core, so that would be set for any plugin doing commits.

But that would likely be a breaking change, so we would bundle that with other breaking changes in a future major release. For now, in order to solve your original issue we can implement that in the `git` plugin in this PR.

**Comment by sergeybekrin** [comment]
@pvdlg I like idea of using native git environment variables, but at same time I like convenience of setting custom `GIT_EMAIL` / `GIT_USERNAME` just once. I think custom env. vars. adds more complexity and native ones are more explicit, so I would vote native git options.

But that's totally up to you, I don't have big picture of `semantic-release` ecosystem, maybe there're already some patterns we can stick to for consistency.

**Comment by pvdlg** [comment]
Ok good point. We can keep the deprecation of `GIT_USERNAME` and `GIT_EMAIL`.
The code I provided as an example is still correct I think.

In next major release we'll remove `GIT_USERNAME` and `GIT_EMAIL` (and probably move all that in the core).

**Comment by sergeybekrin** [comment]
@pvdlg unfortunately I had no time recently, I can continue starting next week. If you think what takes long, feel free to take over.

**Comment by pvdlg** [comment]
No problem, take your time. Just let us know if you can't complete the PR for any reason.

**Pull request closed without merging**
