### PR TITLE
feat: allow empty commit

### PR DESCRIPTION
**Pull request by Grzesie2k**

### CODE REVIEW

**Comment by pvdlg** [comment]
There is no description, what's the point of this PR? Why would the plugin make empty commits?

**Comment by Grzesie2k** [comment]
Zrzut ekranu z 2020-03-09 17-18-56

This option allows us to create release commit and skip CI on release tag without any assets.

**Comment by pvdlg** [comment]
What's the point of creating a commit iff there is no assets to commit?

**Comment by Grzesie2k** [comment]
Unification of release methods (create release tag only on release commit created by this plugin) and allow users to skip ci on release tag with custom commit message (see screenshot above).

**Comment by Grzesie2k** [comment]
Zrzut ekranu z 2020-03-10 16-10-15

**Comment by pvdlg** [comment]
> Unification of release methods (create release tag only on release commit created by this plugin) and allow users to skip ci on release tag with custom commit message (see screenshot above).

Not sure why you would have some releases containing files and some other being empty.
This plugin is meant to push to the repository files like `package.json`, `CHANGELOG.md` or the built assets. Those should be present with every releases.

If you want to push files that are not related to the release process (i.e. files updated with the new version or files generated as part of the release) this is out of the scope of this plugin. 

Regarding the problem of skipping CI on release tag it's a CI configuration issue. Most CI allow to enable/disable builds on tags.

**Pull request closed without merging**
